Let's practice numpy !

In this exercise, you'll have to initialize your own vectors, matrices and tensors and perform basic operations: selecting elements, slicing, masking, reshaping etc...

The last part of the exercise takes advantage of the possibility to draw random values from a known distribution to make you (re-)discover a very famous theorem of Statistics 🤓


# Dealing with vectors ⛹️

1. Import numpy

In [2]:
import numpy as np

2. Initialize a numpy array called vec which contains values from 0 to 10 with a step of 0.5
```
array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])
```

In [3]:
vec = np.array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5.
                , 5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

3. What is the shape of vec ?
```
The shape of vec is:  (21,)
```

In [4]:
print("The shape of vec is {}".format(vec.shape))

The shape of vec is (21,)


4. Display the 7th value of vec
```
The value at index 6 is:  3.0
```

In [5]:
print(vec[6])

3.0


5. Display the 3 first items of vec
```
The 3 first items are:  [0.  0.5 1. ]
```

In [6]:
print(vec[0:3])

[0.  0.5 1. ]


6. Display the 3 last items
```
The 3 last items are:  [ 9.   9.5 10. ]
```

In [7]:
print(vec[-3:])

[ 9.   9.5 10. ]


7. By using masks, select values of vec that are below 7
```
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False])

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5])
```


In [8]:
mask_under_7 = vec < 7

print(vec[mask_under_7])

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]



# Dealing with matrices 🏋️‍♀️
8. Define a function called my_func that takes to arguments x and y, and returns: 
```
f(x) = x^2+y
```

In [9]:
def my_func(x, y):
    return x**2+y

9. Use my_func to initialize a 4x4 matrix:
```
array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])
```

In [10]:
np.fromfunction(my_func, (4,4), dtype = int)

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

10. Iterate other the matrix' values and for each value, find a way of computing its remainder in the integer division by 2.

Hint: There exists an operator (like +or *) that allows to compute the remainder in integer division. Python's doc may help you 😉
```
When dividing 0 by 2, the remainder is: 0
When dividing 1 by 2, the remainder is: 1
When dividing 2 by 2, the remainder is: 0
When dividing 3 by 2, the remainder is: 1
When dividing 1 by 2, the remainder is: 1
When dividing 2 by 2, the remainder is: 0
When dividing 3 by 2, the remainder is: 1
When dividing 4 by 2, the remainder is: 0
When dividing 4 by 2, the remainder is: 0
When dividing 5 by 2, the remainder is: 1
When dividing 6 by 2, the remainder is: 0
When dividing 7 by 2, the remainder is: 1
When dividing 9 by 2, the remainder is: 1
When dividing 10 by 2, the remainder is: 0
When dividing 11 by 2, the remainder is: 1
When dividing 12 by 2, the remainder is: 0
```

In [11]:
mat10 = np.fromfunction(my_func, (4,4), dtype = int)

for i in mat10.flat:
    print(i%2)

0
1
0
1
1
0
1
0
0
1
0
1
1
0
1
0


10. Once you've found the operator that allows to compute the remainder, use it to create a mask that allows to select only even numbers in your matrix. Store these values into an array called even_numbers.
```
array([ 0,  2,  2,  4,  4,  6, 10, 12])
```

In [12]:
mask10 = mat10 % 2 == 0

even_numbers = mat10[mask10]

even_numbers

array([ 0,  2,  2,  4,  4,  6, 10, 12])

11. Reshape even_numbers into a 2x4 matrix and apply the log function to its elements.
```
array([[ 0,  2,  2,  4],
       [ 4,  6, 10, 12]])
<ipython-input-14-d8a89f5ee465>:1: RuntimeWarning: divide by zero encountered in log
  np.log(even_numbers_reshaped)

array([[      -inf, 0.69314718, 0.69314718, 1.38629436],
       [1.38629436, 1.79175947, 2.30258509, 2.48490665]])
```

In [13]:
even_numbers.reshape(2,4)
even_numbers = even_numbers.astype(float)


In [14]:
for i in range(len(even_numbers.flat)):
    even_numbers[i] = np.log2(even_numbers[i])
   
print(even_numbers)

[      -inf 1.         1.         2.         2.         2.5849625
 3.32192809 3.5849625 ]


C:\Users\rapha\AppData\Local\Temp\ipykernel_9936\454866265.py:2: RuntimeWarning: divide by zero encountered in log2
  even_numbers[i] = np.log2(even_numbers[i])


# From vector to matrix, from matrix to tensor and the way back 🤹

12. Initialize a vector named vec containing the 100 first integers:
```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
```

In [15]:
vec = np.array(range(100))

13. Create a 10x10 matrix containing the values of vec
```
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

In [16]:
vec.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

14. We'd like to create a tensor of rank 3 by reshaping the matrix such that it will be structured like several layers of 5x5 matrices. Find a way to do this operation with .reshape:
```
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])
```

In [17]:
vec = vec.reshape(4,5,5)
vec.reshape(4,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

15. Select the tensor's first layer (the first 5x5 matrix)
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

In [18]:
vec[0,:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

16. Among this first layer matrix, select the element at line index 1 and column index 2:
```
7
```

In [19]:
vec[0,1,2]

7

17. Still among the first layer matrix, select all the elements of column 2:
```
array([ 2,  7, 12, 17, 22])
```


In [20]:
vec[0,:,2]

array([ 2,  7, 12, 17, 22])

18. Still among the first layer matrix, select all the elements of line 1:
```
array([5, 6, 7, 8, 9])
```

In [21]:
vec[0,1,:]

array([5, 6, 7, 8, 9])

19. Re-create the initial 10x10 matrix from your tensor
```
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

In [22]:
np.array(range(100)).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

20. Re-create the initial vector of 100 elements from you tensor
```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
```

In [23]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# A famous theorem 🤓
**Let's use numpy's random values generator to re-discover one of the most famous theorems of statistics !**

21. Generate an array named uniform_values containing 10.000 elements that are drawn from a (continuous) uniform distribution in the interval [0, 10].
The cell below allows you to visualize the distribution of the values.
```
import plotly.express as px

px.histogram(uniform_values)
```

In [24]:
uniform_values = np.random.randint(0,10,10000)

import plotly.express as px

px.histogram(uniform_values)

22. Now, create a loop with 1000 iterations. At each iteration:\
Draw a new sample of 10.000 values drawn from a (continuous) uniform distribution in the interval [0, 10]\
Compute the sample's mean (hint: numpy arrays have many useful methods to compute basic statistics)\
Store the mean value into a list named mean_values.\
In the end, you must get a list named mean_values containing 1000 elements. The cell after will allow you to visualize the distribution of the elements in mean_values.
```
px.histogram(mean_values)
```

In [32]:
mean_values = []

for i in range(1000):
    X = np.random.randint(0,10,10000)
    X = np.mean(X)
    
    mean_values.append(X)
    
print(mean_values)

px.histogram(mean_values)


[4.5183, 4.4763, 4.4787, 4.4477, 4.502, 4.5111, 4.5178, 4.5212, 4.5276, 4.5011, 4.4952, 4.5298, 4.4786, 4.4684, 4.5424, 4.505, 4.5257, 4.4638, 4.5101, 4.446, 4.5103, 4.517, 4.5241, 4.5027, 4.4961, 4.5204, 4.4785, 4.4636, 4.4957, 4.5273, 4.4502, 4.4979, 4.5032, 4.5102, 4.5243, 4.5199, 4.495, 4.5036, 4.4638, 4.5098, 4.5405, 4.526, 4.5623, 4.5254, 4.5806, 4.4838, 4.5029, 4.4926, 4.4729, 4.5327, 4.5077, 4.4971, 4.4791, 4.4306, 4.5691, 4.497, 4.4977, 4.4962, 4.4675, 4.4544, 4.5028, 4.526, 4.4402, 4.4756, 4.4732, 4.4706, 4.495, 4.5241, 4.5446, 4.5163, 4.4784, 4.5181, 4.4377, 4.4773, 4.5044, 4.5379, 4.5074, 4.5075, 4.5156, 4.5121, 4.4521, 4.5015, 4.4805, 4.4641, 4.5048, 4.4844, 4.5398, 4.5196, 4.5266, 4.4959, 4.4954, 4.5279, 4.4995, 4.5053, 4.5379, 4.4884, 4.5205, 4.5049, 4.5128, 4.5283, 4.4881, 4.4653, 4.4781, 4.5168, 4.4964, 4.5319, 4.5292, 4.5025, 4.4714, 4.4945, 4.4709, 4.4678, 4.4975, 4.5054, 4.5179, 4.5144, 4.569, 4.4804, 4.5652, 4.5132, 4.4795, 4.4751, 4.5033, 4.4899, 4.5596, 4.4913, 4

23. Do you recognize this curve? Which probability density does it represent ?


In [ ]:
# THIS CURVE REPRESENTS THE BELL CURVE